---
kind: ReplicationController
apiVersion: v1
metadata:
    name: capstoneblue
    labels:
        app: capstoneblue
spec:
    replicas: 1
    selector:
        app: capstoneblue
    template:
        metadata:
            labels:
                app: capstoneblue
        spec:
            containers:
                - name: capstoneblue
                  image: ltapfuma/capstone-udacity
                  ports:
                      - name: http-server
                        containerPort: 80
